name: Release App
permissions: read-all
on:
  push:
    branches:
      - main
      - beta
      - dev
      - staging
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Docker Image
    outputs:
      success: ${{ steps.test-image.outputs.success }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test Docker Image
        id: test-image
        uses: outoforbitdev/action-docker-test@v1.0.0-staging.1
        with:
          test-command: sh ./tests.sh
  release:
    runs-on: ubuntu-latest
    name: Release Image
    needs: test
    if: ${{ needs.test.outputs.success }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Publish Release
        uses: outoforbitdev/action-semantic-release@v1.4.3-staging.2
        id: semantic-release
        with:
          github-token: ${{ secrets.RELEASE_TOKEN }}
          skip-changelog: ${{ github.ref_name != 'main' }}
      - name: Summarize Versions
        env:
          LAST_VERSION: ${{ steps.semantic-release.outputs.last-version }}
          NEXT_VERSION: ${{ steps.semantic-release.outputs.next-version }}
          VERSION_RELEASED: >-
            ${{ steps.semantic-release.outputs.version-released}}
        run: >-
          echo "### Version Summaries" >> $GITHUB_STEP_SUMMARY;
          echo "* Last version - $LAST_VERSION" >> $GITHUB_STEP_SUMMARY;
          echo "* Next version - $NEXT_VERSION" >> $GITHUB_STEP_SUMMARY;
          echo "* Version released - $VERSION_RELEASED" >> $GITHUB_STEP_SUMMARY
      - name: Publish Image
        uses: outoforbitdev/action-docker-publish@v1.2.0-staging.8
        id: docker-publish
        if: ${{ steps.semantic-release.outputs.version-released }}
        with:
          docker-username: ${{ vars.DOCKER_USERNAME }}
          docker-token: ${{ secrets.DOCKER_TOKEN }}
          image-name: ${{ vars.IMAGE_NAME }}
          image-tag: ${{ steps.semantic-release.outputs.next-version }}
      - name: Output Tags
        run: echo "Tag is ${{steps.docker-publish.outputs.sha-tag}}"
